import Head from 'next/head';
import Hero from '../components/Hero';
import LeaderSection from '../components/LeaderSection';
import CreationsSection from '../components/CreationsSection';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Loopstudios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
        <link href="https://fonts.googleapis.com/css2?family=Alata&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Alata&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&display=swap" rel="stylesheet" />
      </Head>

      <main>
       <Hero />
       <LeaderSection />
       <CreationsSection />
       <Footer />
      </main>
    </div>
  )
};